//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 03:30:40 PM WAT 
//


package dz.home.commun.mapping.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dz.home.commun.mapping.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dz.home.commun.mapping.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Attributes }
     * 
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link InputParam }
     * 
     */
    public InputParam createInputParam() {
        return new InputParam();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link InternalParameters }
     * 
     */
    public InternalParameters createInternalParameters() {
        return new InternalParameters();
    }

    /**
     * Create an instance of {@link FunctionDeclare }
     * 
     */
    public FunctionDeclare createFunctionDeclare() {
        return new FunctionDeclare();
    }

    /**
     * Create an instance of {@link FileRelationShip }
     * 
     */
    public FileRelationShip createFileRelationShip() {
        return new FileRelationShip();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link DeclareVariable }
     * 
     */
    public DeclareVariable createDeclareVariable() {
        return new DeclareVariable();
    }

    /**
     * Create an instance of {@link FileKey }
     * 
     */
    public FileKey createFileKey() {
        return new FileKey();
    }

    /**
     * Create an instance of {@link VariableDeclaration }
     * 
     */
    public VariableDeclaration createVariableDeclaration() {
        return new VariableDeclaration();
    }

    /**
     * Create an instance of {@link Function }
     * 
     */
    public Function createFunction() {
        return new Function();
    }

    /**
     * Create an instance of {@link OutputParam }
     * 
     */
    public OutputParam createOutputParam() {
        return new OutputParam();
    }

    /**
     * Create an instance of {@link FilesKeys }
     * 
     */
    public FilesKeys createFilesKeys() {
        return new FilesKeys();
    }

    /**
     * Create an instance of {@link FunctionDeclaration }
     * 
     */
    public FunctionDeclaration createFunctionDeclaration() {
        return new FunctionDeclaration();
    }

    /**
     * Create an instance of {@link ExternalObjectInput }
     * 
     */
    public ExternalObjectInput createExternalObjectInput() {
        return new ExternalObjectInput();
    }

    /**
     * Create an instance of {@link AddField }
     * 
     */
    public AddField createAddField() {
        return new AddField();
    }

    /**
     * Create an instance of {@link Mappings }
     * 
     */
    public Mappings createMappings() {
        return new Mappings();
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link ExternalParameters }
     * 
     */
    public ExternalParameters createExternalParameters() {
        return new ExternalParameters();
    }

}
