//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 03:30:40 PM WAT 
//


package dz.home.commun.mapping.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parameter element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="parameter">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="name">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="ipAdress"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *         &lt;attribute name="type" use="required">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Object"/>
 *               &lt;enumeration value="String"/>
 *               &lt;enumeration value="string"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *         &lt;attribute name="value" use="required">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="1.0"/>
 *               &lt;enumeration value="Asset Information"/>
 *               &lt;enumeration value="Category"/>
 *               &lt;enumeration value="Description"/>
 *               &lt;enumeration value="Granite"/>
 *               &lt;enumeration value="LIVE"/>
 *               &lt;enumeration value="NEC"/>
 *               &lt;enumeration value="NSN"/>
 *               &lt;enumeration value="ON AIR"/>
 *               &lt;enumeration value="RootContainer"/>
 *               &lt;enumeration value="SRAL XD"/>
 *               &lt;enumeration value="Serial Number"/>
 *               &lt;enumeration value="Slot Occupancy"/>
 *               &lt;enumeration value="Status"/>
 *               &lt;enumeration value="TRANSMISSION"/>
 *               &lt;enumeration value="aidNm"/>
 *               &lt;enumeration value="discoveredName"/>
 *               &lt;enumeration value="ehNm"/>
 *               &lt;enumeration value="eqNm"/>
 *               &lt;enumeration value="external:"/>
 *               &lt;enumeration value="external:ipAdress"/>
 *               &lt;enumeration value="function:getRefData"/>
 *               &lt;enumeration value="installedEquipmentObjectType"/>
 *               &lt;enumeration value="ipAdress"/>
 *               &lt;enumeration value="manufacturer"/>
 *               &lt;enumeration value="meNm"/>
 *               &lt;enumeration value="productName"/>
 *               &lt;enumeration value="session:cardCategory"/>
 *               &lt;enumeration value="session:cardEhNm"/>
 *               &lt;enumeration value="session:cardName"/>
 *               &lt;enumeration value="session:eqType"/>
 *               &lt;enumeration value="session:function:CONCAT('/card=',cardName)"/>
 *               &lt;enumeration value="session:function:CONCAT('/rack=',rackName)"/>
 *               &lt;enumeration value="session:function:CONCAT(cardName)"/>
 *               &lt;enumeration value="session:function:CONCAT(shelfName)"/>
 *               &lt;enumeration value="session:function:CONCAT(slotName)"/>
 *               &lt;enumeration value="session:shelfEhNm"/>
 *               &lt;enumeration value="session:siteName"/>
 *               &lt;enumeration value="session:slotEhNm"/>
 *               &lt;enumeration value="version"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "parameter")
public class Parameter {

    @XmlAttribute
    protected String name;
    @XmlAttribute(required = true)
    protected String type;
    @XmlAttribute(required = true)
    protected String value;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
