//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 03:30:40 PM WAT 
//


package dz.home.commun.mapping.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parameters element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="parameters">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}InternalParameters"/>
 *           &lt;element ref="{}externalParameters" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "internalParameters",
    "externalParameters"
})
@XmlRootElement(name = "parameters")
public class Parameters {

    @XmlElement(name = "InternalParameters", required = true)
    protected InternalParameters internalParameters;
    protected ExternalParameters externalParameters;

    /**
     * Gets the value of the internalParameters property.
     * 
     * @return
     *     possible object is
     *     {@link InternalParameters }
     *     
     */
    public InternalParameters getInternalParameters() {
        return internalParameters;
    }

    /**
     * Sets the value of the internalParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalParameters }
     *     
     */
    public void setInternalParameters(InternalParameters value) {
        this.internalParameters = value;
    }

    /**
     * Gets the value of the externalParameters property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalParameters }
     *     
     */
    public ExternalParameters getExternalParameters() {
        return externalParameters;
    }

    /**
     * Sets the value of the externalParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalParameters }
     *     
     */
    public void setExternalParameters(ExternalParameters value) {
        this.externalParameters = value;
    }

}
